export const SAVE_TEMPLATE_REQUEST = "SAVE_TEMPLATE_REQUEST";
export const SAVE_TEMPLATE_REQUEST_FAILED = "SAVE_TEMPLATE_REQUEST_FAILED";
export const SAVE_TEMPLATE_REQUEST_SUCCESS = "SAVE_TEMPLATE_REQUEST_SUCCESS";
export const DELETE_TEMPLATE_REQUEST = "DELETE_TEMPLATE_REQUEST";
export const DELETE_TEMPLATE_REQUEST_FAILED = "DELETE_TEMPLATE_REQUEST_FAILED";
export const DELETE_TEMPLATE_REQUEST_SUCCESS =
  "DELETE_TEMPLATE_REQUEST_SUCCESS";
export const GET_TEMPLATE_LIST_REQUEST = "GET_TEMPLATE_LIST_REQUEST";
export const GET_TEMPLATE_LIST_REQUEST_SUCCESS =
  "GET_TEMPLATE_LIST_REQUEST_SUCCESS";
export const GET_TEMPLATE_LIST_REQUEST_FAILED =
  "GET_TEMPLATE_LIST_REQUEST_FAILED";
export const SET_TEMPLATE_TYPE_REQUEST = "SET_TEMPLATE_TYPE_REQUEST";
export const SEND_EMAIL_REQUEST = "SEND_EMAIL_REQUEST";
export const SEND_EMAIL_REQUEST_SUCCESS = "SEND_EMAIL_REQUEST_SUCCESS";
export const SEND_EMAIL_REQUEST_FAILED = "SEND_EMAIL_REQUEST_FAILED";
export const SEND_SMS_REQUEST = "SEND_SMS_REQUEST";
export const SEND_SMS_REQUEST_SUCCESS = "SEND_SMS_REQUEST_SUCCESS";
export const SEND_SMS_REQUEST_FAILED = "SEND_SMS_REQUEST_FAILED";
export const SET_RESPONSE_TO_DEFAULT = "SET_RESPONSE_TO_DEFAULT";
export const SET_ERROR_TO_DEFAULT = "SET_ERROR_TO_DEFAULT";
export const SET_TEMPLATE_OBJECT_TO_EMPTY = "SET_TEMPLATE_OBJECT_TO_EMPTY";
export const VIEW_TEMPLATE_REQUEST = "VIEW_TEMPLATE_REQUEST";
export const VIEW_TEMPLATE_REQUEST_SUCCESS = "VIEW_TEMPLATE_REQUEST_SUCCESS";
export const VIEW_TEMPLATE_REQUEST_FAILED = "VIEW_TEMPLATE_REQUEST_FAILED";
export const EDIT_TEMPLATE_REQUEST = "EDIT_TEMPLATE_REQUEST";
export const EDIT_TEMPLATE_REQUEST_SUCCESS = "EDIT_TEMPLATE_REQUEST_SUCCESS";
export const EDIT_TEMPLATE_REQUEST_FAILED = "EDIT_TEMPLATE_REQUEST_FAILED";
export const SET_READY = "SET_READY";
