export const GENERATE_TOKEN_REQUEST = "GENERATE_TOKEN_REQUEST";
export const GENERATE_TOKEN_REQUEST_SUCCESS = "GENERATE_TOKEN_REQUEST_SUCCESS";
export const GENERATE_TOKEN_REQUEST_FAILED = "GENERATE_TOKEN_REQUEST_FAILED";
export const VERIFY_TOKEN_REQUEST = "VERIFY_TOKEN_REQUEST";
export const VERIFY_TOKEN_REQUEST_SUCCESS = "VERIFY_TOKEN_REQUEST_SUCCESS";
export const VERIFY_TOKEN_REQUEST_FAILED = "VERIFY_TOKEN_REQUEST_FAILED";
export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_REQUEST_SUCCESS = "VERIFY_OTP_REQUEST_SUCCESS";
export const VERIFY_OTP_REQUEST_FAILED = "VERIFY_OTP_REQUEST_FAILED";
export const SIGN_OUT = "SIGN_OUT";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAILED = "REFRESH_TOKEN_FAILED";
export const GENERATE_STAFF_TOKEN_REQUEST = "GENERATE_STAFF_TOKEN_REQUEST";
export const GENERATE_STAFF_TOKEN_REQUEST_SUCCESS =
  "GENERATE_STAFF_TOKEN_REQUEST_SUCCESS";
export const GENERATE_STAFF_TOKEN_REQUEST_FAILED =
  "GENERATE__STAFF_TOKEN_REQUEST_FAILED";
export const VERIFY_STAFF_TOKEN_REQUEST = "VERIFY_STAFF_TOKEN_REQUEST";
export const VERIFY_STAFF_TOKEN_REQUEST_SUCCESS =
  "VERIFY_STAFF_TOKEN_REQUEST_SUCCESS";
export const VERIFY_STAFF_TOKEN_REQUEST_FAILED =
  "VERIFY_STAFF_TOKEN_REQUEST_FAILED";
